### ISSUE TITLE
Error in inf[[1]] : subscript out of bounds 

### ISSUE THREAD

**Issue by srbehera** [t-arae/ngscmdr#1]
I am getting `Error in inf[[1]] : subscript out of bounds` error when I execute this line  `df <- merge_featurecount_output(in_dir="./readcount")`. The `readcount `directory has the featurecount txt files.

**Comment by t-arae** [comment]
Thanks for reporting this issue.

In `in_dir`, there must be both files whose names end with `"gene_counts.txt"` and `"transcript_counts.txt"`. 
Please check the file names in the specified directory.

**Comment by srbehera** [comment]
Thanks !! Could you please explain what are these two files? Are there any sample test files in this repository. I have only  `featureCounts.txt` and `featureCounts.summary` files.

**Comment by t-arae** [comment]
Sorry, there are no sample files in this repository.


Both of those files are the output from `featureCounts` which reporting the read-count on the genes or transcripts.
The file counting the reads for genes is `"*gene_counts.txt"`, and the file counting the reads for transcripts is `"*transcript_counts.txt”`.
The reason for this is that I used to count reads not only for genes but also for transcripts.

In your case, I think `featureCounts.txt` is the read-count file.

`merge_featurecount_output()` does not care what files in the folder are counting for, but the current implementation may fail if both files are missing.

If you are only counting reads for genes now, a simple way to do this is 
1. Duplicate one of the read-count files as a dummy file and rename it to `"transcript_counts.txt”`
2. Then, change the end of the name of the other read-counts files to `"gene_counts.txt"`.
